---
- name: roles/postgresql/tasks/init.yml
  command: echo
- name: Check if database exists
  stat:
    path: "{{ PG_DATADIR }}/PG_VERSION"
  register: pg_data
  become: yes
  become_user: postgres
# - debug: var=pg_data
- name: Initialize database instance
  shell: "{{ PG_INITDB }}"
  become: yes
  become_user: postgres
  when: pg_data.stat.exists == false
- name: Check for grant access from localhost
  shell: grep -v trust$ {{ PG_DATADIR }}/pg_hba.conf >& /dev/null
  register: trust_not_found
  become: yes
  ignore_errors: yes
- name: Grant access from localhost
  copy: 
    src:    pg_hba.conf
    dest:   "{{ PG_DATADIR }}"
    owner:  postgres
    group:  postgres
    mode:   0600
    force:  yes
  when: trust_not_found.rc == 0
  become: yes
- name: Enable postgresql service
  service:
    name: "{{ PG_SERVICE }}"
    enabled:  yes
    state:  restarted
  become: yes
