---
- name: roles/postgresql/tasks/package.yml
  include_vars: vars/centos{{ ansible_distribution_major_version }}.yml
- name: Remove old postgresql data
  file: path=/var/lib/pgsql/data state=absent
  become: yes
- name: Install PGDG repository
  yum: name={{ PG_REPO_URI }} state=present
  become: yes
- name: Install postgresql packages
  yum: name={{item}} state=present
  with_items:
    - postgresql{{ PG_VERSION }}-server
    - postgresql{{ PG_VERSION }}-devel
    - "{{ PHP_PKG_PREFIX }}-pgsql"
    - python-psycopg2
  become: yes
- name: Add {{ PG_BIN_DIR }} to $PATH
  template:
    src: pgsql.sh
    dest: /etc/profile.d
  become: yes
