# GitBucket
---
- name: roles/gitbucket/tasks/main.yml
  command: echo

- name: Create effective user
  user:
    name: "{{ GITBUCKET_USER }}"
    append: yes
    home: "{{ GITBUCKET_HOME }}"
    system: yes
  become: yes

- name: Prepare directory for war file
  file:
    state:  directory
    path:   "{{ GITBUCKET_WAR_DIR }}"
  become: yes

- name: Prepare directory for log file
  file:
    state:  directory
    path:   "{{ GITBICKET_LOG_DIR }}"
    owner:  "{{ GITBUCKET_USER }}"
  become: yes

- name: Get archive file
  get_url:
    url: https://github.com/gitbucket/gitbucket/releases/download/{{ GITBUCKET_VERSION }}/gitbucket.war
    dest: "{{ GITBUCKET_WAR_FILE }}"
  become: yes

- name: Put an environment file
  template:
    src:  etc/sysconfig/gitbucket
    dest: /etc/sysconfig/
  become: yes

- name: Make it a service
  template:
    src: usr/lib/systemd/gitbucket.service
    dest: /usr/lib/systemd/system/
  become: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Start GitBucket Service
  systemd:
    name: gitbucket
    state: started
    enabled:  yes
  become: yes
